### ISSUE TITLE
Realtime security deployment

### ISSUE THREAD

**Issue by Pasarus** [fiaisis/gitops#15]
For this we have a couple options and the options need to be evaluated appropriately:

- https://github.com/controlplaneio/kubesec (Free?)
- https://www.spyderbat.com/ (Free with limits, 5 nodes, just prod, bigger nodes? culling app worker nodes and just having very large nodes?)
- https://github.com/aquasecurity/trivy (Perhaps something to deploy at the same time as a realtime scanner like spyderbat?)
- https://falco.org/ (Free)

For Falco deployment:
Falco Alert -> Prometheus -> Groundcover -> Alertmanager -> OnCall alerts (The right way)
Falco -> SMTP -> On Call email (The quick dirty way)

**Comment by keiranjprice101** [comment]
Falco deployed
